import React from 'react';
import './App.css';
import NormalForm from './FormNormal';
import AutoGeneratedForm from './FormAutoGenerated';

function App() {
  return (
    <div className="App">
      <div className="container">
        <div className="row">
          <div className="col-sm">
            <NormalForm />
          </div>
          <div className="col-sm">
            <AutoGeneratedForm />
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
